//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.Educat.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class currentsession
    {
        public string sessionname { get; set; }
        public int term { get; set; }
        public System.DateTime nexttermbegins { get; set; }
        public int nooftimesschoolopens { get; set; }
        public bool isOpened { get; set; }
        public int schoolid { get; set; }
    
        public virtual schoolsetup schoolsetup { get; set; }
    }
}
