//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.Educat.Models.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EducatContext : DbContext
    {
        public EducatContext()
            : base("name=EducatContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arm> Arms { get; set; }
        public virtual DbSet<@class> classes { get; set; }
        public virtual DbSet<commentsonresult> commentsonresults { get; set; }
        public virtual DbSet<currentsession> currentsessions { get; set; }
        public virtual DbSet<grade> grades { get; set; }
        public virtual DbSet<parent> parents { get; set; }
        public virtual DbSet<schoolsetup> schoolsetups { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<studentsubjectregistrationandresult> studentsubjectregistrationandresults { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
    }
}
