//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.Educat.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class schoolsetup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public schoolsetup()
        {
            this.currentsessions = new HashSet<currentsession>();
        }
    
        public int Id { get; set; }
        public string schoolname { get; set; }
        public string locationaddress { get; set; }
        public byte[] logo { get; set; }
        public string email { get; set; }
        public string phoneno { get; set; }
        public string currentsession { get; set; }
        public int currentterm { get; set; }
        public string schoolshortname { get; set; }
        public double cascore { get; set; }
        public double examscore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<currentsession> currentsessions { get; set; }
    }
}
