//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.Educat.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.commentsonresults = new HashSet<commentsonresult>();
            this.studentsubjectregistrationandresults = new HashSet<studentsubjectregistrationandresult>();
        }
    
        public long Id { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string othername { get; set; }
        public string gender { get; set; }
        public System.DateTime dob { get; set; }
        public int currentclassId { get; set; }
        public string currentsession { get; set; }
        public int currentterm { get; set; }
        public int armId { get; set; }
        public string guardiannames { get; set; }
        public string guardianphoneno { get; set; }
        public string guardianemail { get; set; }
        public string homeaddress { get; set; }
        public string city { get; set; }
        public Nullable<int> state { get; set; }
        public int yearofentry { get; set; }
        public bool graduated { get; set; }
        public int yearofgraduation { get; set; }
        public byte[] picture { get; set; }
        public long parentid { get; set; }
    
        public virtual Arm Arm { get; set; }
        public virtual @class @class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commentsonresult> commentsonresults { get; set; }
        public virtual parent parent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<studentsubjectregistrationandresult> studentsubjectregistrationandresults { get; set; }
    }
}
